### PR TITLE
The number of iterator records are now customizable.

### PR DESCRIPTION
**Pull request by mscappini**
This is actually my first fork and pull request, as well as writing solid unit test code with Moq. Please let me know if anything needs to be changed or improved. I tried to follow the direction of @jsgoupil to write consistent unit tests.

Also, is there a better way to set that `MaxReturned` property without a harness class?

### CODE REVIEW

**Comment by jsgoupil** [comment]
Hey I have been a bit busy, I'll look at that soon!

**Comment by mscappini** [comment]
Great! I tried to get this in because now I am looking at changing the iterator size for my work project. :smile:

**Comment by jsgoupil** [comment]
@mscappini Since you asked the question about the Harness class test, have you thought of putting a property on the StepQueryWithIterator class that would take an integer MaxRequest?

**Comment by mscappini** [comment]
I hadn't considered it. I always feel that if you have a settable property that is supposed to be mirrored across two or more classes, those properties have the ability to become out of sync for one reason or another.

**Comment by jsgoupil** [comment]
@mscappini OK no problem.

**Pull request merged**
