### PR TITLE
Canadian taxforms

### PR DESCRIPTION
**Pull request by rogerfar**
I added the following taxforms for Canadian companies to the enumeration on the XSD:
- FormT1
- FormT2
- Form1044
- Form3010

Unfortunately QuickBooks has this bug open for over 4 years now, so I doubt they are fixing it anytime soon in their XSD's.

If you don't want to mess with the official XSD's I understand!

### CODE REVIEW

**Comment by jsgoupil** [comment]
I'm all for it, but can you revert the non modified version please ?

**Comment by rogerfar** [comment]
Makes sense, done.

**Comment by jsgoupil** [comment]
Do you need this to be released or it can wait a bit? Maybe you'll have more pull requests for your project :) ?

**Comment by rogerfar** [comment]
I'm in no hurry no. I just went through an overhaul to get rid of some technical debt on our platform, this was really the only thing that was bugging me :)

**Comment by jsgoupil** [comment]
I put a reminder on my calendar on the 20th. If nothing happens, I'll release this.

**Pull request merged**
