### PR TITLE
Support correct decimal for float and amt types.

### LINKED ISSUE #56: decimal precision in QUANTYPE
Hello, we are trying to send quantities such as 0.16667 as the quantity on a CreditMemoLineAdd, and the QBXML being generated is 0.17.

I believe this is due to the use of  
`return _value.ToString("F", CultureInfo.InvariantCulture);`

in the FLOATTYPE superclass. Since (I believe) QBXML supports 5 decimal places, would "F5" be more appropriate here?

### PR DESCRIPTION
**Pull request by jsgoupil**
Fix #56

### CODE REVIEW

**Comment by jsgoupil** [comment]
@Davidcc I updated the code.

@tofer Can you review please?

**Comment by jsgoupil** [comment]
This would be released as a patch.

**Review by tofer — COMMENTED** [review]
Without grabbing this PR and actually testing with QB, this looks good to me.

I'm fairly certain the 'G5' format won't use commas for the thousands separator here, but that could be one additional test you add (assuming QB would be picky about that)

**Review by tofer — COMMENTED** [review]
Total oversight by me here. The G5 pattern will show 5 total digits, not 5 decimal places. N5 will include the comma. Do we know if that's an issue?

I'd suggest we use `ToString("0.#####")`

**Pull request merged**
