### PR TITLE
Add package details to csproj files.  Update create-nuget batch file.

### PR DESCRIPTION
**Pull request by adamskt**
Unfortunately, the Owners and Summary tags are not supported: https://docs.microsoft.com/en-us/nuget/schema/msbuild-targets#pack-target

### CODE REVIEW

**Comment by jsgoupil** [comment]
Sounds fine, the Summary doesn't seem to be used on NuGet but the ID and Description are. I'll play with them.
Thanks for fixing this.

**Comment by adamskt** [comment]
Happy to help!  The new packages look functionally the same when opened with NPE
chrome_2018-01-16_12-44-41
chrome_2018-01-16_12-43-47

**Comment by jsgoupil** [comment]
@adamskt Thank you! I have submitted the packages on NuGet today.
Sorry for the super long delay and thanks for all the work!

**Comment by adamskt** [comment]
Happy to help!

**Pull request merged**
